# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    node_8_ubuntu:
      node_version: 8.x
      vm: 'Ubuntu-16.04'
    node_10_ubuntu:
      node_version: 10.x
      vm: 'Ubuntu-16.04'
    node_8_vs2017:
      node_version: 8.x
      vm: 'VS2017'
    node_10_vs2017:
      node_version: 10.x
      vm: 'VS2017'

pool:
  vmImage: '$(vm)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
    yarn install
    yarn test
  displayName: 'Test using AVA'
